<?php


return [
    "zones" => [
        "Broken Shore",
        "Suramar",
        "Azsuna",
        "Highmountain",
        "Val'sharah",
        "Twisting Nether",
        "Stormheim",
        "Faralohn",
        "Tanaan Jungle",
        "Ashran",
        "Nagrand",
        "Spires of Arak",
        "Talador",
        "Gorgrond",
        "Frostfire Ridge",
        "Shadowmoon Valley",
        "Isle of Giants",
        "Tanaan Jungle",
        "Vale of Eternal Blossoms",
        "Isle of Thunder",
        "Timeless Isle",
        "Dread Wastes",
        "Townlong Steppes",
        "The Storm Peaks",
        "Icecrown",
        "Zul'Drak",
        "Dragonblight",
        "Howling Fjord",
        "Borean Tundra",
        "Shadowmoon Valley",
        "Netherstorm",
        "Blade's Edge Mountains",
        "Nagrand",
        "Terokkar Forest",
        "Zangarmarsh",
        "Hellfire Peninsula",
        "Blasted Lands",
        "Silithus",
        "Stranglethorn Vale",
        "Desolace",
        "Southern Barrens",
        "Arathi Highlands",
        "Alterac Mountains",
        "Stonetalon Mountains",
        "Duskwood",
        "Wetlands",
        "Ashenvale",
        "Hillsbrad Foothills",
        "Redridge Mountains",
        "Loch Modan",
        "Darkshore",
        "Bloodmyst Isle",
        "Northern Barrens",
        "Silverpine Forest",
        "Ghostlands",
        "Azshara",
        "Westfall",
        "Azuremyst Isle",
    ]
];